### ISSUE TITLE
ItemView

### ISSUE THREAD

**Issue by mBigFlower** [Qiaoidea/QQTipsView#1]
你好。首先感谢你的控件。
提一个小问题。加载你的工程的时候（Eclipse）
drawSouceBitmap(canvas, alpha);
drawTargetBitmap(alpha);
这两句话里面会crash，后来找到原因mIconBitmap为空，后来我改成这样
if (mIconBitmap != null)
            canvas.drawBitmap(mIconBitmap, null, mIconRect, getPaint(255 - alpha));
发现下面的四个tab没了图片。
而在layout.xml里确实是有的
<code.qiao.com.tabview.TabItemView
                android:id="@+id/tab2"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:padding="5dp"
                test:icon="@drawable/tab3"
                test:text="发现"
                test:text_size="10sp" />
不知道为什么，获取不到

对了 这里我改了个东西 因为attr里提示冲突了。我改成了
name="tips_icon" format="reference"
name="tips_color" format="color"

Drawable drawable = a.getDrawable(R.styleable.TabItemView_tips_icon);
应该不会有影响吧

**Comment by mBigFlower** [comment]
<attr name="tips_icon" format="reference" />
        <attr name="tips_color" format="color" />

**Comment by Qiaoidea** [comment]
底部tab的话是随便画的，问题很多，还有待重写。。这里主要是分享拖动删除功能的。

好久没过来看了，见谅
